// export const SET_DAYS_IN_WEEK = 'CALENDAR/SET_DAYS_IN_WEEK';
// export const SET_DAYS_IN_MONTH = 'CALENDAR/SET_DAYS_IN_MONTH';
// export const SET_WEEKS_IN_MONTH = 'CALENDAR/SET_WEEKS_IN_MONTH';
// export const SET_MONTHS_IN_YEAR = 'CALENDAR/SET_MONTHS_IN_YEAR';
export const SET_DAYS_IN_YEAR = 'CALENDAR/SET_DAYS_IN_YEAR';
// export const SET_CURRENT_WEEK_IN_MONTH = 'CALENDAR/SET_CURRENT_WEEK_IN_MONTH';